spring.application.name=webapp

# PostgreSQL DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# AWS Configuration
# aws.s3.bucket-name=your-bucket-name
# aws.s3.region=us-east-1

# Spring Multipart Upload Limits
# spring.servlet.multipart.max-file-size=25MB
# spring.servlet.multipart.max-request-size=25MB
# aws.access-key-id=YOUR_ACCESS_KEY
# aws.secret-access-key=YOUR_SECRET_KEY

spring.jackson.deserialization.fail-on-null-for-primitives=false